{{ range $name,$ns := .Values.namespaces }}
{{ $commonresources := default (dict) $.Values.common.resources }}
{{ $nsresources := default (dict) $ns.resources }}
{{ $resources := mergeOverwrite (deepCopy $commonresources) $nsresources }}
{{- $defaults := $resources.defaults }}
{{- if $defaults }}
apiVersion: v1
kind: LimitRange
metadata:
  name: {{ $name }}
  namespace: {{ $name }}
  labels:
    {{- include "tenant.chartlabels" $ | nindent 4 }}
    {{- include "tenant.commonlabels" $ | nindent 4 }}
    {{- include "tenant.labels" $ns | nindent 4 }}
  {{- if $ns.annotations }}
  annotations:
    {{- toYaml $ns.annotations | nindent 4 }}
  {{- end }}
spec:
  limits:
  - type: Container
    {{ if $defaults.limits -}}
      default:
        {{- toYaml $defaults.limits | nindent 6 }}
    {{ end -}}
    {{ if $defaults.requests -}}
    defaultRequest:
      {{- toYaml $defaults.requests | nindent 6 }}
    {{ end }}
---
{{ end -}}
{{ end -}}
