{{ range $name,$ns := .Values.namespaces }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $name }}
  labels:
    namespaceName: {{ $name }}
    {{- include "tenant.chartlabels" $ | nindent 4 }}
    {{- include "tenant.commonlabels" $ | nindent 4 }}
    {{- include "tenant.labels" $ns | nindent 4 }}
  annotations:
  {{- if $ns.annotations }}
    {{- toYaml $ns.annotations | nindent 4 }}
  {{- end }}
---
{{ end -}}
