{{ range $name,$ns := .Values.namespaces }}
{{ if $ns.network }}
{{ if $ns.network.allowExternal }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $name }}
  namespace: {{ $name }}
  labels:
    {{- include "tenant.chartlabels" $ | nindent 4 }}
    {{- include "tenant.commonlabels" $ | nindent 4 }}
    {{- include "tenant.labels" $ns | nindent 4 }}
  {{- if $ns.annotations }}
  annotations:
    {{- toYaml $ns.annotations | nindent 4 }}
  {{- end }}
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
---
{{ end -}}
{{ end -}}
{{ end -}}
