{{ range $name,$ns := .Values.namespaces }}
{{- if $ns.resources }}
{{- if $ns.resources.quotas }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ $name }}
  namespace: {{ $name }}
  labels:
    {{- include "tenant.chartlabels" $ | nindent 4 }}
    {{- include "tenant.commonlabels" $ | nindent 4 }}
    {{- include "tenant.labels" $ns | nindent 4 }}
  {{- if $ns.annotations }}
  annotations:
    {{- toYaml $ns.annotations | nindent 4 }}
  {{- end }}
spec:
  hard:
    {{- toYaml $ns.resources.quotas | nindent 4 }}
---
{{ end -}}
{{ end -}}
{{ end -}}
