labels:
  app: gw-internal
  gw-type: internal

gateway:
  create: true
  gatewayClassName: gwclass-name
  listeners:
    web:
      port: 80
      protocol: HTTP
      hostname: "*.example.com"

httproutes:
  rt1:
    uriprefix: "a-prefix"
    destination: svc1
    namespace: ns1
  rt2:
    hosts:
    - rt2.example.com
    uriprefix: "a-prefix"
    destination: svc2
    namespace: ns2
    port: 8181
  rt3:
    hosts:
    - rt3.example.com
    rules:
    - backendRefs:
      - name: foo
        port: 80
