gateway:
  gatewayClassName: gwclass-name
  listeners:
    web:
      port: 80
      protocol: HTTP
      hostname: "*.example.com"
      tls:
        certificateRefs:
          name: foo
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              foo: bar
