gateway:
  name: existing-gw

httproutes:
  rt1:
    uriprefix: "a-prefix"
    namespace: ns1
    destination:
      name: svc1
  rt2:
    hosts:
    - rt2.example.com
    uriprefix: "a-prefix"
    namespace: ns2
    destination:
      name: svc2
    port: 8181
  rt3:
    hosts:
    - rt3.example.com
    rules:
    - backendRefs:
      - name: foo
        port: 80
