labels: {}

gateway:
  # -- Gateway name defaults to a name based on the chart release name. Also used for httpRoutes, including when no gateway resource is created
  name: 
  gatewayClassName: 
  listeners: {}
  #   web:
  #     port: 80
  #     protocol: HTTP
  #     # -- Hostname (optional). Wildcards are allowed
  #     hostname: 

httproutes: {}
  # example-route:
  #   hosts:
  #   - example-route.example.com
  #   uriprefix: example-prefix
  #   destination: example-service
  #   namespace: example-namespace
  #   port: 8181
