labels: {}

gateway:
  # -- Create Gateway. A non-nil list of listeners also enable Gateway creation. If no Gateway is created the HTTPRoutes should be mesh attached.
  create: false
  # -- Gateway name defaults to a name based on the chart release name. Also used for HTTPRoutes, including when no gateway resource is created
  name:
  gatewayClassName:
  # -- List of gateway listeners. Gateway resources are only created if at least one listener is defined
  listeners: {}
  #   web:
  #     port: 80
  #     protocol: HTTP
  #     # -- Hostname (optional). Wildcards are allowed
  #     hostname:
  # -- Optional list of addresses to associate with the gateway
  addresses: []

httproutes: {}
  # example-route:
  #   hosts:
  #   - example-route.example.com
  #   uriprefix: example-prefix
  #   destination: example-service
  #   namespace: example-namespace
  #   port: 8181
  #   meshAttached: false

# -- Create ReferenceGrant for all HTTPRoute's that have an explicit namespace.
referencegrant:
  # -- Create ReferenceGrant for HTTPRoutes
  enabled: true
