# Gateway API version
gatewayAPIVersion: "0.6.0"

labels: {}

gateway:
  # -- Create Gateway. A non-nil list of listeners also enable Gateway creation. If no Gateway is created the HTTPRoutes should be mesh attached.
  create: false
  # -- Gateway name defaults to a name based on the chart release name. Also used for HTTPRoutes, including when no gateway resource is created
  name:
  # -- Namespace where to create Gateway resource or when `gateway.create` is false then the namespace of an existing Gateway
  namespace:
  gatewayClassName:
  # -- List of gateway listeners. Gateway resources are only created if at least one listener is defined
  listeners: {}
  #   web:
  #     port: 80
  #     protocol: HTTP
  #     # -- Hostname (optional). Wildcards are allowed
  #     hostname:
  #     allowedRoutes:
  #       namespaces:
  #         from: Selector
  #         selector:
  #           matchLabels:
  #             foo: bar
  # -- Optional list of addresses to associate with the gateway
  addresses: []

httproutes: {}
  # example-route:
  #   hosts:
  #   - example-route.example.com
  #   uriprefix: example-prefix
  #   destination:
  #     # -- Service name
  #     name: example-service
  #     # -- Namespace of service
  #     namespace: example-namespace
  #   # -- Namespace of HTTPRoute
  #   namespace: example-namespace
  #   port: 8181
  #   meshAttached: false

# -- Create ReferenceGrant for all HTTPRoute's that have an explicit namespace.
referencegrant:
  # -- Create ReferenceGrant for HTTPRoutes
  enabled: true
  # -- Enable ReferenceGrant for Gateways. Not part of the core spec.
  enableForGatewayReferences: false
