{{- range $rt,$spec := .Values.httproutes }}
apiVersion: gateway.networking.k8s.io/{{ include "gateway-api.httpRouteVersion" . }}
kind: HTTPRoute
metadata:
  name: {{ $rt }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- with $.Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  parentRefs:
  {{- if $.Values.gateway.create -}}
  - kind: Gateway
    name: {{ default (include "gateway-api.fullname" $) $.Values.gateway.name }}
  {{- end -}}
  {{- if $spec.meshAttached -}}
  - kind: Mesh
    name: istio
  {{- end -}}
  {{- if $spec.hosts }}
  hostnames:
  {{- range $spec.hosts }}
  - {{ . | quote }}
  {{- end -}}
  {{- end -}}
  {{- if $spec.rules }}
  rules:
    {{- toYaml $spec.rules | nindent 2 }}
  {{- else if $spec.destination }}
  rules:
  - backendRefs:
    - name: {{ $spec.destination }}
      port: {{ default 80 $spec.port }}
      {{- if $spec.namespace }}
      namespace: {{ $spec.namespace }}
      {{- end }}
    {{- if $spec.uriprefix }}
    matches:
    - path:
        type: PathPrefix
        value: {{ $spec.uriprefix }}
    {{- end -}}
  {{- end }}
---
{{- end }}
