{{- range $rt,$spec := .Values.httproutes }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ $rt }}
  labels:
    {{- with $.Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  parentRefs:
  - kind: Gateway
    name: {{ default (include "gateway-api.fullname" $) $.Values.gateway.name }}
  hostnames:
  {{- range $spec.hosts }}
  - {{ . }}
  {{- end }}
  rules:
    {{- toYaml $spec.rules | nindent 2 }}
---
{{- end }}
