{{- range $rt,$spec := .Values.httproutes }}
# If no HTTPRoute destination or rules are given, no HTTPRoute is rendered
{{- if (or $spec.destination $spec.rules) }}
apiVersion: gateway.networking.k8s.io/{{ include "gateway-api.httpRouteVersion" $ }}
kind: HTTPRoute
metadata:
  name: {{ $rt }}
  namespace: {{ default $.Release.Namespace $spec.namespace }}
  labels:
    {{- include "gateway-api.labels" $ | nindent 4 }}
spec:
  parentRefs:
  {{- if $spec.meshAttached }}
  - kind: Mesh
    name: istio
  {{- else }}
  - kind: Gateway
    name: {{ default (include "gateway-api.fullname" $) $.Values.gateway.name }}
    namespace: {{ default $.Release.Namespace $.Values.gateway.namespace }}
  {{- end -}}
  {{- if $spec.hosts }}
  hostnames:
  {{- range $spec.hosts }}
  - {{ . | quote }}
  {{- end -}}
  {{- end -}}
  {{- if $spec.rules }}
  rules:
    {{- toYaml $spec.rules | nindent 2 }}
  {{- else if $spec.destination }}
  rules:
  - backendRefs:
    - name: {{ $spec.destination.name }}
      port: {{ default 80 $spec.destination.port }}
      namespace: {{ default (default $.Release.Namespace $spec.namespace) $spec.destination.namespace }}
      {{- if $spec.destination.weight }}
      weight: {{ $spec.destination.weight }}
      {{- end }}
  {{- end -}}
  {{- if $spec.uriprefix }}
    matches:
    - path:
        type: PathPrefix
        value: {{ $spec.uriprefix }}
  {{- end }}
---
{{- end -}}
{{- end }}
