{{- if .Values.referencegrant.enabled -}}
# Create ReferenceGrant for all HTTPRoutes that have explicit namespace
{{- range $rt,$spec := .Values.httproutes }}
{{- if $spec.namespace }}
apiVersion: gateway.networking.k8s.io/{{ include "gateway-api.referenceGrantVersion" $ }}
kind: ReferenceGrant
metadata:
  name: {{ $rt }}
  namespace: {{ $spec.namespace }}
  labels:
    {{- include "gateway-api.labels" $ | nindent 4 }}
spec:
  from:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    namespace: {{ $.Release.Namespace }}
  to:
  - group: ""
    kind: Service
---
{{- end }}
{{- end }}
{{- end }}
